"""Bind opt-in operator messaging to a bounded profile policy at gateway launch."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path

from zeus.envfile import quote_env_value
from zeus.hermes_profile_config import load_hermes_profile_config
from zeus.hermes_profile_environment import load_hermes_profile_environment
from zeus.private_io import nofollow_absolute_path, read_private_bytes

_POLICY_KEYS = frozenset(
    {"ZEUS_MESSAGES_ENABLED", "API_SERVER_ENABLED", "API_SERVER_PORT", "API_SERVER_KEY"}
)
_MANAGED_DIRECTORY = Path("/etc/hermes")


class MessagePolicyError(ValueError):
    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


@dataclass(frozen=True)
class MessagePolicy:
    fingerprint: str
    api_key: str
    credential_fingerprint: str


def load_message_policy(profile_path: Path, *, require_enabled: bool = True) -> MessagePolicy:
    try:
        environment = load_hermes_profile_environment(profile_path / ".env")
        if require_enabled and environment.get("ZEUS_MESSAGES_ENABLED") != "1":
            raise MessagePolicyError("messaging_disabled")
        raw_env = read_private_bytes(nofollow_absolute_path(profile_path / ".env"), 65536)
        _validate_environment(raw_env.decode("utf-8"), environment)
        if "HERMES_MANAGED_DIR" in environment or _MANAGED_DIRECTORY.exists():
            raise MessagePolicyError("managed_policy_unsupported")
        if (profile_path / "gateway.json").exists():
            raise MessagePolicyError("legacy_policy_unsupported")
        config = load_hermes_profile_config(profile_path / "config.yaml")
        agent = config.get("agent")
        gateway = config.get("gateway")
        if not isinstance(agent, dict) or not isinstance(gateway, dict):
            raise MessagePolicyError("message_limits_required")
        max_turns = _positive_integer(agent.get("max_turns"))
        api_server = gateway.get("api_server")
        if (
            max_turns is None
            or not 1 <= max_turns <= 100
            or not isinstance(api_server, dict)
            or _positive_integer(api_server.get("max_concurrent_runs")) != 1
        ):
            raise MessagePolicyError("message_limits_required")
        soul = read_private_bytes(nofollow_absolute_path(profile_path / "SOUL.md"), 65536)
        api_key = environment["API_SERVER_KEY"]
        credential = hashlib.sha256(api_key.encode("utf-8")).hexdigest()
        policy = json.dumps(
            {
                "config": config,
                "soul": hashlib.sha256(soul).hexdigest(),
                "api_port": environment["API_SERVER_PORT"],
                "credential": credential,
            },
            sort_keys=True,
            ensure_ascii=True,
            separators=(",", ":"),
            allow_nan=False,
        )
        return MessagePolicy(hashlib.sha256(policy.encode()).hexdigest(), api_key, credential)
    except MessagePolicyError:
        raise
    except (OSError, UnicodeError, ValueError, TypeError, KeyError) as exc:
        raise MessagePolicyError("configuration_invalid") from exc


def _positive_integer(value: object) -> int | None:
    # The restricted YAML reader retains scalar text; Hermes converts these
    # two fields to integers. Reject interpolation and alternate spellings.
    if type(value) is int:
        return value
    if isinstance(value, str) and re.fullmatch(r"[1-9][0-9]{0,2}", value):
        return int(value)
    return None


def _validate_environment(text: str, environment: dict[str, str]) -> None:
    # These values must mean the same thing to Zeus and python-dotenv. Require
    # the literal serialization generated by Zeus, with no expansion/duplicates.
    seen: set[str] = set()
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        name = line.partition("=")[0].removeprefix("export ").strip().strip("'\"")
        if name == "HERMES_MANAGED_DIR":
            raise MessagePolicyError("managed_policy_unsupported")
        if name not in _POLICY_KEYS:
            continue
        value = environment.get(name, "")
        if name in seen or "$" in value or line != f"{name}={quote_env_value(value)}":
            raise MessagePolicyError("configuration_invalid")
        seen.add(name)
    key = environment.get("API_SERVER_KEY", "")
    if re.fullmatch(r"[A-Za-z0-9._~+/@%=:,\-]{16,4096}", key) is None:
        raise MessagePolicyError("credentials_unavailable")
    port = environment.get("API_SERVER_PORT", "")
    if (
        environment.get("API_SERVER_ENABLED") != "1"
        or not port.isascii()
        or not port.isdecimal()
        or not 1 <= int(port) <= 65535
        or not _POLICY_KEYS.issubset(seen)
    ):
        raise MessagePolicyError("configuration_invalid")
